export const resortData = [
  {
    "ResortTitle": "Sandals Montego Bay",
    "Island": "Jamaica",
    "ResortDescription": "The original flagship Sandals \nSet on Jamaica’s largest white-sand beach\nClose proximity to Montego Bay's attractions and nightlife\nShort trip to Dunn’s River Falls experience\n12 Restaurants and 6 bars\n7 freshwater pools and 3 whirlpools\nPADI-Certified SCUBA diving and equipment \nSnorkeling, waterskiing, wakeboarding, paddleboards, and kayaks \nDay and night tennis and a range of land activities \nFitness Center and Red Lane Spa",
    "IdealFor": "Pool Lovers",
    "IdealFor2": "Beach Lovers",
    "IdealFor3": "Food and Drink Lovers",
    "Tags": "adults-only, more-social, more-intimate, long-stretch, scuba, motorized-watersports, tennis, swim-up-suites, jerk-shack, british-pub,  steakhouse, sushi, distance-to-airport-less-than-45-minutes \n",
    "Images": "/images/Sandals Montego Bay/1 - Carousel_ResortHero_Slider/Sandals-SMB-BeachAerial-6.jpg",
    "Beaches": "/images/Sandals Montego Bay/1 - Carousel_ResortHero_Slider/Sandals-SMB-BeachAerial-6.jpg",
    "Pool": "images/Sandals Montego Bay/3 - Pools/Sandals-SMB-Swim-Up.jpg",
    "Map": "",
    "Dining": "images/Sandals Montego Bay/5 - Dining & Bars/Sandals-SMB-Cricketers2.jpg",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Royal Caribbean Resort",
    "Island": "Jamaica",
    "ResortDescription": "Jamaica’s only resort with a private offshore island\nThe Caribbean’s first Over-the-Water Bungalows & Villas\nDaily “Rum and Royals” mixology events (I would delete this)\nLucea Shark Encounter excursion (Martha Brea Rafting is a better excursion)\n9 restaurants and 5 bars\n8 pools, including a swim-up pool bar\nPADI-Certified SCUBA diving and equipment\nHobie Cats, paddleboards, and kayaks\nCroquet and other land sports\nFitness Center and Red Lane Spa ",
    "IdealFor": "Food and Drink Lovers",
    "IdealFor2": "Adventure",
    "IdealFor3": "Water Sports Lovers",
    "Tags": "adults-only, more-tranquil, more-intimate, offshore-island, scuba, over-the-water-villas, jerk-shack, british-pub, distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Royal Caribbean/1 - Carousel_ResortHero_Slider/Sandals-Royal-Caribbean-Offshore-Island.jpg",
    "Beaches": "images/Sandals Royal Caribbean/4 - Beaches/Sandals-SRC-BeachAerial-7.jpg",
    "Pool": "images/Sandals Royal Caribbean/3 - Pools/Sandals-Royal-Caribbean-Swim-ups.jpg",
    "Map": "",
    "Dining": "images/Sandals Royal Caribbean/5 - Dining & Bars/src-104.jpg",
    "watersports": "",
    "IslandTours": "images/Sandals Royal Caribbean/Offshore island/Sandals-SRC-BeachAerial-3.jpg"
  },
  {
    "ResortTitle": "Sandals Negril",
    "Island": "Jamaica",
    "ResortDescription": "Set on the longest stretch of Negril’s Seven Mile Beach\nDaily sunset drum ritual (I’m not sure we do this and would suggest we remove)\nEasy access to eco-reef adventure \nEasy access to deep-sea fishing \nPADI-Certified SCUBA diving and equipment\n8 restaurants and 5 bars\n4 pools and 3 whirlpools\nWaterskiing, wakeboarding, and glass bottom boatTennis, croquet, and a wide range of land sports\nFitness Center and Red Lane Spa ",
    "IdealFor": "Beach Lovers",
    "IdealFor2": "Adventure Lovers",
    "IdealFor3": "Watersports Lovers",
    "Tags": "adults-only, more-tranquil, more-intimate, long-stretch-of-beach, scuba, glass-bottom-boat, tennis, sky-pool-suite, swim-up-suite, motorized-watersports, teppanyaki, distance-to-airport-more-than-an-hour  \n",
    "Images": "images/Sandals Negril/1 - Carousel_ResortHero_Slider/Sandals-Negril-Aerial.jpg",
    "Beaches": "images/Sandals Negril/4 - Beaches/Sandals-Negril-Aerial.jpg",
    "Pool": "images/Sandals Negril/3 - Pools/Sandals-Negril-Pool.jpg",
    "Map": "",
    "Dining": "images/Sandals Negril/5 - Dining & Bars/Sandals-Negril-Bar.jpg",
    "watersports": "images/Sandals Negril/6 - Watersports/Sandals-Negril-Scuba-Pool.jpg",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Ochi Beach Resort",
    "Island": "Jamaica",
    "ResortDescription": "Easy access to the Bob Marley Reggae and Culture Tour\nFeatures the Ochi Beach Club \n7 main pools, 98 villa pools, and 22 whirlpools\n16 Restaurants and 11 bars\nCaribbean’s first speakeasy bar, the Rabbit Hole\nEasy access to Jamaica’s most elite and popular golf course \nThe Caribbean’s largest Rock-Climbing Wall (30’ X 30’)\nPADI-Certified SCUBA diving and equipment\nTennis and pickleball courts \nFitness Center and Red Lane Spa",
    "IdealFor": "Golf Lovers",
    "IdealFor2": "Food and Drink Lovers",
    "IdealFor3": "Pool Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, nearby-golf-course, glass-bottom-boat, tennis, pickleball, jerk-shack, sushi, teppanyaki, distance-to-airport-more-than-an-hour  \n",
    "Images": "images/Sandals Ochi/1 - Carousel_ResortHero_Slider/Sandals-Ochi-Main-Pool.jpg",
    "Beaches": "images/Sandals Ochi/4 - Beaches/Sandals-Ochi-Beach.jpg",
    "Pool": "images/Sandals Ochi/3 - Pools/Sandals-Ochi-Great-House-Village.jpg",
    "Map": "",
    "Dining": "images/Sandals Ochi/5 - Dining & Bars/Sandals-Ochi-Kellys.jpg",
    "watersports": "images/Sandals Ochi/6 - Watersports/Sandals-Ochi-Beach-Kayaks.jpg",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Royal Plantation",
    "Island": "Jamaica",
    "ResortDescription": "All views are ocean-views\nFeatures two private cove beaches \nThe Caribbean’s only champagne and caviar bar \nEnglish-style afternoon tea service\nHome to the exclusive Villa Plantana\n Free green fees and transfers to the nearby Sandals Golf & Country Club\n PADI-Certified SCUBA diving and equipment \n5 restaurants and 3 bars\nAccess to all amenities at nearby Sandals Ochi\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Beach Lovers",
    "IdealFor2": "Food and Drink Lovers",
    "IdealFor3": "Golf Lovers",
    "Tags": "adults-only, more-tranquil, more-intimate, scuba, cove-beach, glass-bottom-boat, tennis, british-pub, distance-to-airport-more-than-an-hour  \n",
    "Images": "images/Sandals Royal Plantation/1 - Carousel_ResortHero_Slider/croissantsandcaviar_sandalsroyalplantation-15.jpg",
    "Beaches": "",
    "Pool": "",
    "Map": "",
    "Dining": "",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals South Coast",
    "Island": "Jamaica",
    "ResortDescription": "Set on a 2-mile stretch of Jamaica's south coast's most pristine white-sand beach\nLocated within a 500-acre nature preserve\nEasy access to the Appleton Estate Historic Rum Tour (Pelican Bar or YS Falls might be a better option)\nThree beachfront pools, including Jamaica’s largest zero-entry pool\n9 restaurants and 7 bars\nBeachside food trucks \nOver-the-water bar, Latitudes\nPADI-Certified SCUBA diving and equipment\nTennis and pickleball courts\nFitness Center and Red Lane Spa",
    "IdealFor": "Beach Lovers",
    "IdealFor2": "Nature Lovers",
    "IdealFor3": "Food and Wine Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, long-stretch-of-beach, tennis, pickleball, motorized-watersports, over-the-water-villa, rondoval-suite, swim-up-suite, jerk-shack, sushi, distance-to-airport-more-than-an-hour  \n",
    "Images": "images/Sandals Royal Plantation/1 - Carousel_ResortHero_Slider/croissantsandcaviar_sandalsroyalplantation-15.jpg",
    "Beaches": "images/Sandals Royal Plantation/4 - Beaches/SRP_Beach_Detail.jpg",
    "Pool": "images/Sandals Royal Plantation/3 - Pools/croissantsandcaviar_sandalsroyalplantation-4.jpg",
    "Map": "",
    "Dining": "images/Sandals Royal Plantation/5 - Dining & Bars/SRP_PAPILLON_TERRACE_.jpg",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Dunn’s River",
    "Island": "Jamaica",
    "ResortDescription": "Sandals’ newest property in Jamaica, in the heart of Ochos Rios  \nEasy access to forests, rivers, and waterfalls \nTreetop zipline, river tubing, and blue hole experience\n PADI-Certified SCUBA diving and equipment\nUnlimited water sports\n Table Tennis, shuffleboard, bocce Ball, beach volleyball, croquet, and cricket\n Long river pools\nTransfers and greens fees at Upton Estate Golf and Country Club (should it state free transfers)\n2 restaurants and 9 bars\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Adventure Lovers",
    "IdealFor2": "Golf Lovers",
    "IdealFor3": "Food and Drink Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, rondoval-suite, swim up-suite, off-property-golf, jerk-shack, distance-to-airport-more-than-an-hour  \n",
    "Images": "images/Sandals Dunn's River/1 - Carousel_ResortHero_Slider/Sandals_Dunns_River_Beach.jpg",
    "Beaches": "images/Sandals Dunn's River/4 - Beaches/Sandals_Dunns_River_Beach.jpg",
    "Pool": "images/Sandals Dunn's River/3 - Pools/Sandals_Dunns_River_Pool_Whirlpool.jpg",
    "Map": "",
    "Dining": "images/Sandals Dunn's River/5 - Dining & Bars/Sandals_Dunns_River_SKYBAR.jpg",
    "watersports": "",
    "IslandTours": "images/Sandals Dunn's River/7 - Tours/Dunns_River_Falls.jpg"
  },
  {
    "ResortTitle": "Sandals Emerald Bay (Bahamas)",
    "Island": "Bahamas",
    "ResortDescription": "The ultimate golf, tennis & spa resort\nSitting on one mile of one of Exuma’s best powdery beaches \nHalf acre zero entry pool \nPADI-Certified SCUBA diving and equipment\nTransfers and geens fees to Greg Norman designed golf course   \n6 tennis courts, including a sunken stadium\nPickleball court\n11 restaurants and 6 bars\nExuma Bays swimming with pigs adventure \nFitness Center and Red Lane Spa",
    "IdealFor": "Golf Lovers",
    "IdealFor2": "Tennis Lovers",
    "IdealFor3": "Beach Lovers",
    "Tags": "adults-only, more-social, more-intimate, scuba, long-stretch-of-beach, tennis, pickleball, golf-off-property, british-pub, jerk-shack, sushi, teppanyaki, distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Emerald Bay/1 - Carousel_ResortHero_Slider/Drone_MainPool_0030.jpg",
    "Beaches": "images/Sandals Emerald Bay/4 - Beaches/EB_Drone_Beach_shore_007 RGB.jpg",
    "Pool": "images/Sandals Emerald Bay/3 - Pools/Drone_MainPool_0030.1.jpg",
    "Map": "",
    "Dining": "",
    "watersports": "images/Sandals Emerald Bay/6 - Watersports/CPL Boat_2_0247.jpg",
    "IslandTours": "images/Sandals Emerald Bay/7 - Tours/Pig_Island_0298 (1).jpg"
  },
  {
    "ResortTitle": "Sandals Royal Bahamian",
    "Island": "Bahamas",
    "ResortDescription": "The Bahamas’ most elegant resort \nFeaturing its own private offshore island\nEasy access to the Blue Lagoon dolphin swim\nRolls Royce private transfers for top-tier suites \nOver 10,000 sq. ft of freshwater pools \nPADI-Certified SCUBA diving and equipment\n10 restaurants and 8 bars\nEasy access to Nassau for shopping, tours, and casinos \nClose proximity to Miami \nFitness Center and Red Lane Spa",
    "IdealFor": "Food and Drink Lovers",
    "IdealFor2": "Island Lovers",
    "IdealFor3": "Pool Lovers",
    "Tags": "adults-only, more-social, more-intimate, scuba, long-stretch-of-beach, tennis, pickleball, golf-off-property, british-pub, jerk-shack, sushi, teppanyaki, distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Royal Bahamian/1 - Carousel_ResortHero_Slider/SRB - Aerial Beach 1.jpg",
    "Beaches": "images/Sandals Royal Bahamian/4 - Beaches/SRB - Aerial Barefoot Cay 2.jpg",
    "Pool": "images/Sandals Royal Bahamian/3 - Pools/SRB - Aerial East Bay Pool 2.jpg",
    "Map": "",
    "Dining": "images/Sandals Royal Bahamian/5 - Dining & Bars/la_Plume_10077_RET.jpg",
    "watersports": "images/Sandals Royal Bahamian/6 - Watersports/SBS_ 1399.jpg",
    "IslandTours": "images/Sandals Royal Bahamian/7 - Tours/Pig_Island_0298.jpg"
  },
  {
    "ResortTitle": "Sandals Grenada Resort & Spa (Grenada)",
    "Island": "Grenada",
    "ResortDescription": "Located in the southeastern Caribbean on Pink Gin Beach\nVolcanic island with exotic black sand beaches\nEasy access to rainforests, waterfalls, and mountain lakes\nEasy access to deep sea fishing adventure \nBalthazar River Tubing Adventure\nDiving and snorkeling at the underwater sculpture park \nPADI-Certified SCUBA diving and all equipment\n10 restaurants and 6 bars\n5 pools and 2 whirlpools\nFitness Center and Red Lane Spa \n",
    "IdealFor": "Dive Lover",
    "IdealFor2": "Adventure Lovers",
    "IdealFor3": "Nature Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, tennis, swim-up-suite, tennis, british-pub, sushi, teppanyaki, distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Grenada/1 - Carousel_ResortHero_Slider/GRENEDA_SANDALS_DISKIN-161.jpg",
    "Beaches": "images/Sandals Grenada/4 - Beaches/Sandals-Grenada-02-2022-Beaches 2-5156.jpg",
    "Pool": "images/Sandals Grenada/3 - Pools/GRENEDA_SANDALS_DISKIN-161.1.jpg",
    "Map": "",
    "Dining": "images/Sandals Grenada/5 - Dining & Bars/GRENEDA_SANDALS_DISKIN-146.jpg",
    "watersports": "images/Sandals Grenada/6 - Watersports/Sandals-Grenada-02-2022-Beaches-4212.jpg",
    "IslandTours": "images/Sandals Grenada/7 - Tours/Sandals-Grenada-02-2022-Grand-Anse-Beach-4581.jpg"
  },
  {
    "ResortTitle": "Sandals Barbados",
    "Island": "Barbados",
    "ResortDescription": "Situated on the pristine white sands of Dover Beach\nSet along the largest and longest river pool in Barbados\n 21 restaurants and 14 bars\nWalking distance to shopping and nightlife in St. Lawrence Gap\nAll amenities at adjacent Sandals Royal Barbados\nPADI-Certified SCUBA diving and equipment\nHobie Cats, paddleboards, kayaks and glass-bottom boat\nBowling at Lovers Lanes\n11 pools and 6 whirlpools\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Beach Lovers",
    "IdealFor2": "Pool Lovers",
    "IdealFor3": "Food and Drink Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, swim-up-suite, tennis, glass-bottom-boat, bowling, teppanyaki, sushi, steakhouse, british-pub , distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Barbados/1 - Carousel_ResortHero_Slider/IMG_9234.jpg",
    "Beaches": "images/Sandals Barbados/5 - Dining & Bars/SBR_TIKI_BEACH_BAR_0290.jpg",
    "Pool": "",
    "Map": "",
    "Dining": "",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Royal Barbados",
    "Island": "Barbados",
    "ResortDescription": "Largest glass-fronted infinity pool in the Eastern Caribbean \nWonders of Barbados underwater submarine night tour\nBarbados historical rum tour\nAll suites include tranquility soaking tubs for two \nSwim-up bar\nLovers Lane bowling alley and craft beer bar\n 21 restaurants and 14 bars\n11 freshwater pools and six whirlpools\nPADI-Certified SCUBA diving and equipment\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Pool Lovers",
    "IdealFor2": "Food and Drink Lovers",
    "IdealFor3": "Dive Lovers",
    "Tags": "adults-only, more-social, more-expansive, scuba, swim-up-suite, skypool-suite, rondovol-villa, tennis, bowling, steakhouse, jerk shack, distance-to-airport-less-than-45-minutes \n",
    "Images": "images/Sandals Royal Barbados/1 - Carousel_ResortHero_Slider/SBR_SAINT_LAWRENCE_HOUSE_EXT_MAGIC_072.jpg",
    "Beaches": "images/Sandals Royal Barbados/4 - Beaches/SBR_MAIN_POOL_DRONE_0113.jpg",
    "Pool": "images/Sandals Royal Barbados/3 - Pools/SBR_MAIN_POOL_DRONE_0053.jpg",
    "Map": "",
    "Dining": "images/Sandals Royal Barbados/5 - Dining & Bars/SBR_THE_GREENHOUSE_INT_V3_062.jpg",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Halcyon Beach",
    "Island": "St. Lucia",
    "ResortDescription": "A “Garden of Eden” with tropical gardens along pristine white-sand beaches\nThe Caribbean’s longest swim-up pool\nStay at 1, play at 3 – full and easy access to 2 other Sandals resorts \n6 restaurants and 7 bars\n9 hole golf course located nearby at Sandals Regency La Toc \nPADI-Certified SCUBA diving and equipment\n3 pools, 3 whirlpools, 1 SCUBA pool\nWaterskiing, wakeboarding\nHobie Cats, paddleboards, kayaks\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Pool Lovers",
    "IdealFor2": "Golf Lovers",
    "IdealFor3": "Water Sports Lovers",
    "Tags": "adults-only, more-tranquil, more-intimate, scuba, golf-nearby, tennis, motorized-watersports, swim-up-suite, rondovol-villa, teppanyaki, sushi, distance-to-airport-more-than-an-hour \n",
    "Images": "images/Sandals Halcyon Beach/1 - Carousel_ResortHero_Slider/SHC Drone.jpg",
    "Beaches": "images/Sandals Halcyon Beach/4 - Beaches/SHC Drone.jpg",
    "Pool": "",
    "Map": "",
    "Dining": "",
    "watersports": "images/Sandals Halcyon Beach/6 - Watersports/DJI_0164.jpg",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Regency La Toc",
    "Island": "St. Lucia",
    "ResortDescription": "Saint Lucia’s most glamourous resort\nHalf-mile, crescent-shaped beach\nSet against exotic coral bluffs, lush hillsides and rolling fairways\nStay at 1, play at 3 – full and easy access to 2 other Sandals resorts\nSunset Bluff Millionaire Butler Villas with private pool sanctuary \nSandals Regency La Toc Golf course with 9 holes located directly on the resort \n9 restaurants and 8 bars\n3 pools and 4 whirlpools\nPADI-Certified SCUBA diving and equipment\nFitness Center and Red Lane Spa ",
    "IdealFor": "Beach Lovers\n",
    "IdealFor2": "Nature Lovers",
    "IdealFor3": ". Golf Lovers",
    "Tags": "",
    "Images": "images/Sandals Regency La Toc/1 - Carousel_ResortHero_Slider/SLU Drone 3.jpg",
    "Beaches": "images/Sandals Regency La Toc/4 - Beaches/SLU Drone 4-2.jpg",
    "Pool": "images/Sandals Regency La Toc/3 - Pools/SLU Drone 1.jpg",
    "Map": "",
    "Dining": "",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Grande St. Lucian",
    "Island": "St. Lucia",
    "ResortDescription": "Located on Rodney Bay peninsula, known for the calmest waters in Saint Lucia\nMile-long beach with views of volcanic mountains\nLagoon swim-up rooms with direct pool access from the patio \n Stay at 1, play at 3 – full and easy access to 2 other Sandals resorts\n PADI® Certified SCUBA diving and equipment \nGreg Norman designed golf course \n12 restaurants and 6 bars\n8 Over the Water Bungalows\n5 pools, 3 whirlpools, 1 SCUBA pool\nFitness Center and Red Lane Spa\n",
    "IdealFor": "Beach Lovers\n",
    "IdealFor2": "Golf Lovers",
    "IdealFor3": "Food and Drink Lovers.",
    "Tags": "Adults Only \nMore Tranquil\nMore Expansive (Number of Suites: 311 Rooms)\nScuba – Need info if “from resort” or “off resort” (from resort)\nLong stretch of beach\nGolf on the resort\nOver the Water Villas \nRondoval Villa\nSwim Up Suite \nTennis\nBritish Pub, Jerk Shack, Sushi, Teppanyaki \nDistance to Airport: More than an hour \n",
    "Images": "images/Sandals Grande St. Lucian/1 - Carousel_ResortHero_Slider/DJI_0091.jpg",
    "Beaches": "images/Sandals Grande St. Lucian/4 - Beaches/SGL Lifestyle Drone.jpg",
    "Pool": "images/Sandals Grande St. Lucian/3 - Pools/DJI_0874.jpg",
    "Map": "",
    "Dining": "",
    "watersports": "",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Sandals Royal Curacao",
    "Island": "Curacao",
    "ResortDescription": "44 oceanfront acres\nCuracao Caves & Turtle Swim Experience\n8 restaurants and 13 bars\n9 pools\nSwim-up and overwater bar\n3 food trucks with diverse food options\nPADI-Certified SCUBA diving and equipment\nAccess to your own Convertible MINI Cooper*to explore Curaçao \nBeach volleyball and a wide range of land sports\nFitness Center and Red Lane Spe",
    "IdealFor": "Food and Drink Lovers",
    "IdealFor2": "Pool Lovers",
    "IdealFor3": "Sport Lovers",
    "Tags": "Adults Only, More Tranquil, More Expansive (Number of Suites: 351 Rooms), Scuba, Swim Up Suite, Rondoval Villa , Steakhouse, Sushi , Distance to Airport: Less than 45 minutes \n",
    "Images": "images/Sandals Royal Curacao/1 - Carousel_ResortHero_Slider/croissantsandcaviar_sandalsroyalcuracao_resort-8.jpg",
    "Beaches": "images/Sandals Royal Curacao/4 - Beaches/untitled-194(B).jpg",
    "Pool": "images/Sandals Royal Curacao/3 - Pools/untitled-185.jpg",
    "Map": "",
    "Dining": "images/Sandals Royal Curacao/5 - Dining & Bars/Food Truck Toteki SCR_FOOD_TRUCKS_V2_0309.jpg",
    "watersports": "images/Sandals Royal Curacao/6 - Watersports/untitled-124.jpg",
    "IslandTours": "images/Sandals Royal Curacao/7 - Tours/untitled-30.jpg"
  },
  {
    "ResortTitle": "Sandals Grande Antigua",
    "Island": "Antigua",
    "ResortDescription": "Consistently voted the “World’s Most Romantic Resort” \nLocated on Antigua’s best and most famous beach, Dickenson Bay\nSix-Star Mediterranean and Beachfront Villages\nAntigua Rainforest Zipline & Eco-Kayak Experience\nGreat Bird Island Eco & Snorkeling Experience\n6 restaurants and 7 bars\n6 pools and 6 whirlpools \nPADI-Certified SCUBA diving and equipment\nHobie Cats, paddleboards, kayaks\nFitness Center and Red Lane Spa",
    "IdealFor": "Nature Lovers",
    "IdealFor2": ". Pool Lovers",
    "IdealFor3": "Watersports Lovers.",
    "Tags": "Adults Only, More Tranquil, More Intimate, Long stretch of beach, Scuba,, Tennis, Rondoval Villa, Teppanyaki, British Pub, Sushi, Distance to Airport: Less than 45 minutes ",
    "Images": "images/Sandals Grande Antigua/1 - Carousel_ResortHero_Slider/SANDALS_07_2019_BEACH_PADDLEBOARD_COUPLE_6830-370-123.jpg",
    "Beaches": "images/Sandals Grande Antigua/4 - Beaches",
    "Pool": "images/Sandals Grande Antigua/3 - Pools/7H6A7577.jpg",
    "Map": "",
    "Dining": "images/Sandals Grande Antigua/5 - Dining & Bars/SANDALS_07_2019_BEACH_DINNER_489-434-140.jpg",
    "watersports": "images/Sandals Grande Antigua/6 - Watersports/7H6A6522.jpg",
    "IslandTours": "images/Sandals Grande Antigua/7 - Tours/3A6A9655.jpg"
  },
  {
    "ResortTitle": "Sandals Saint Vincent",
    "Island": "Saint Vincent",
    "ResortDescription": "Sandals’ newest resort\nNestled between two seas at the edge of the Lesser Antilles\nCumberland Rainforest Hike\nLover's Rock Sunset Cruise \nOverwater villas \n11 restaurants and 9 bars\nPADI-Certified SCUBA diving and equipment\n4 pools, 2 whirlpools, 1 SCUBA pool\nTennis and and wide range of land sports\nFitness Center and Red Lane Spa\n",
    "IdealFor": "",
    "IdealFor2": "Dive Lovers",
    "IdealFor3": "Sport Lovers",
    "Tags": "adults-only, more-tranquil, more-expansive, scuba, tennis, overwater villas, swim-up-suites, steakhouse, Sushi, Jerk Shack, distance-to-airport-less-than-45-minutes\n",
    "Images": "images/Sandals Saint Vincent/1 - Carousel_ResortHero_Slider/Sandals-Saint-Vincent-aerial-beach.jpg",
    "Beaches": "images/Sandals Saint Vincent/4 - Beaches/Sandals-Saint-Vincent-beach.jpg",
    "Pool": "images/Sandals Saint Vincent/3 - Pools/Sandals-Saint-Vincent-Heart-Shape-Pool.jpg",
    "Map": "",
    "Dining": "images/Sandals Saint Vincent/5 - Dining & Bars/BUTCHES BOOTH_030.jpg",
    "watersports": "images/Sandals Saint Vincent/6 - Watersports/SSV - Saint Vincent Destination 76.jpg",
    "IslandTours": "images/Sandals Saint Vincent/7 - Tours/SSV - Saint Vincent Destination 42.jpg"
  },
  {
    "ResortTitle": "Beaches Ocho Rios",
    "Island": "Jamaica",
    "ResortDescription": "Set on 22 acres of lush tropical garden and a private white sand beach \nPirates Island Waterpark features waterslides, kid-friendly pools and a lazy river\nPADI-Certified SCUBA diving and equipment\nProfessional instruction for water sports\nHobie Cats, paddleboards, kayaks\nTennis and a wide range of land sports\nState-of-the-art fitness center\nSesame Street® themed activities with daily character appearance\nKids Camp with certified nannies\nThe Caribbean’s first certified Autism Centers\n",
    "IdealFor": "Family Fun. ",
    "IdealFor2": "Watersports",
    "IdealFor3": "Golf Lovers",
    "Tags": "families-with-kids, more-social, more-expansive, scuba, tennis, golf-off-property, distance-to-airport-more-than-an-hour \n",
    "Images": "images/Beaches Ocho Rios/1 - Carousel_ResortHero_Slider/BBO_Beach.jpg",
    "Beaches": "images/Beaches Ocho Rios/4 - Beaches/BBO_Beach_2_Drone_.jpg",
    "Pool": "images/Beaches Ocho Rios/3 - Pools/BBO_Pool_Bar.jpg",
    "Map": "",
    "Dining": "images/Beaches Ocho Rios/5 - Dining & Bars/OPA_2301.jpg",
    "watersports": "images/Beaches Ocho Rios/6 - Watersports/BBO_Drone_Waterpark_Detail.jpg",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Beaches Negril",
    "Island": "Jamaica",
    "ResortDescription": "Located on the widest stretch of Negril’s seven-mile white sand beach \nHome to the Pirates Island Water Theme Park with 8 waterslides\nPADI-Certified SCUBA diving and equipment\nWaterskiing, Hobie Cats, paddleboards, kayaks\nProfessional instruction for water sports\nTennis and a wide range of land sports\nState-of-the-art fitness center\nSesame Street® themed activities with daily character appearances\nKids Kamp & Nursery with a wide range of supervised activities \nThe Caribbean’s first certified Autism Centers\n",
    "IdealFor": "Family Fun",
    "IdealFor2": "Watersports",
    "IdealFor3": "Beach Lover",
    "Tags": "families-with-kids, more-social, more-expansive, long-stretch-of-beach, scuba, tennis, distance-to-airport-more-than-an-hour \n",
    "Images": "images/Beaches Negril/1 - Carousel_ResortHero_Slider/DJI_0935 copy.jpg",
    "Beaches": "images/Beaches Negril/4 - Beaches/Beaches Negril_Beach_4.jpg",
    "Pool": "images/Beaches Negril/3 - Pools/DJI_0820.jpg",
    "Map": "",
    "Dining": "images/Beaches Negril/5 - Dining & Bars/Brava.jpg",
    "watersports": "images/Beaches Negril/6 - Watersports/DJI_0796.jpg",
    "IslandTours": ""
  },
  {
    "ResortTitle": "Beaches Turks & Caicos",
    "Island": "Turks & Caicos",
    "ResortDescription": "Situated on world-renowned Grace Bay\n Five vacations in one – with five different villages\nADI-Certified SCUBA diving and equipment at one of the best-ranked dive sites in the world\n10 pools, 4 whirlpools & 1 scuba diving pool\nHome to Pirate’s Island, featuring a surfing park, 8 waterslides, and a kids-only swim-up bar\nProfessional instruction for water sports including Hobie Cats, paddleboards, kayaks\n24 dining options and 14 bars\nState-of-the-art fitness center\nSesame Street® themed activities with daily character appearance\nThe Caribbean’s first certified Autism Centers\n",
    "IdealFor": "Family Fun",
    "IdealFor2": "Watersports",
    "IdealFor3": "Dive Lovers",
    "Tags": "families-with-kids, more-social, more-expansive, scuba, tennis, teppanyaki, sushi, british-pub, distance-to-airport: less-than-45-minutes\n",
    "Images": "images/Beaches Turks and Caicos/1 - Carousel_ResortHero_Slider/DJI_20240120093216_0798_D-Edit.1.jpg",
    "Beaches": "images/Beaches Turks and Caicos/4 - Beaches/DJI_20240120093216_0798_D-Edit.jpg",
    "Pool": "images/Beaches Turks and Caicos/3 - Pools/BTC_ITALIAN_POOL20-6-963-Edit.jpg",
    "Map": "",
    "Dining": "images/Beaches Turks and Caicos/5 - Dining & Bars/DSC_7834-Edit1.jpg",
    "watersports": "images/Beaches Turks and Caicos/6 - Watersports/221213_BeachesTC_S19_DRONE_Waterpark_07250_SB_RGB.jpg",
    "IslandTours": "images/Beaches Turks and Caicos/7 - Tours/221213_BeachesTC_S26_DRONE_Horses_09216_SB_RGB.jpg"
  }
]